spring:

  application:
    name: monitor-notification-matcher

  kafka:
    bootstrap-servers: ${KAFKA_BROKER_ADDR:localhost:9092}
    consumer:
      notify:
        topic: ${NOTIFICATION_MATCH_TOPIC:notification-match}
        group-id: ${CONSUMER_GROUP_NAME:notification-match-consumer-group}
        max-attempts: ${MAX_ATTEMPTS:5}
        backoff-delay: ${BACKOFF_DELAY:1000}
        concurrency: ${CONCURRENT_LISTENER_INSTANCES:1}

  internal:
    api:
      url: ${PRIVATE_API_URL:http://api.chs.local:4001}
      key: ${CHS_INTERNAL_API_KEY:default-internal-api-key}

  external:
    links:
      chs-url: ${CHS_URL:http://chs.local}
      monitor-url: ${CHS_MONITOR_GUI_URL:http://follow.chs.local}

  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://mongo:27017}
      database: ${MONGO_DATABASE:monitor}

management:
  endpoints:
    web.exposure.include: health
  endpoint:
    health.show-details: always
  health:
    defaults.enabled: true
  server:
    port: 8082

server:
  port: ${PORT:8181}
